var jsonData = [
  {
    state: "ANDHRA PRADESH",
    num_lgd_state_code: 28,
    State_wise_sanctioned_projects: 22,
    number_of_proposal_submitted: 339,
  },
  {
    state: "ARUNACHAL PRADESH",
    num_lgd_state_code: 12,
    State_wise_sanctioned_projects: 20,
    number_of_proposal_submitted: 17,
  },
  {
    state: "ASSAM",
    num_lgd_state_code: 18,
    State_wise_sanctioned_projects: 36,
    number_of_proposal_submitted: 216,
  },
  {
    state: "BIHAR",
    num_lgd_state_code: 10,
    count: 21,
    number_of_proposal_submitted: 121,
  },
  {
    state: "CHANDIGARH",
    num_lgd_state_code: 4,
    count: 3,
    number_of_proposal_submitted: 106,
  },
  {
    state: "CHHATTISGARH",
    num_lgd_state_code: 22,
    count: 7,
    number_of_proposal_submitted: 103,
  },
  {
    state: "DELHI",
    num_lgd_state_code: 7,
    count: 44,
    number_of_proposal_submitted: 451,
  },
  {
    state: "GOA",
    num_lgd_state_code: 30,
    count: 6,
    number_of_proposal_submitted: 67,
  },
  {
    state: "GUJARAT",
    num_lgd_state_code: 24,
    count: 18,
    number_of_proposal_submitted: 242,
  },
  {
    state: "HARYANA",
    num_lgd_state_code: 6,
    count: 7,
    number_of_proposal_submitted: 128,
  },
  {
    state: "HIMACHAL PRADESH",
    num_lgd_state_code: 2,
    count: 12,
    number_of_proposal_submitted: 118,
  },
  {
    state: "JAMMU AND KASHMIR",
    num_lgd_state_code: 1,
    count: 22,
    number_of_proposal_submitted: 172,
  },
  {
    state: "JHARKHAND",
    num_lgd_state_code: 20,
    count: 28,
    number_of_proposal_submitted: 221,
  },
  {
    state: "KARNATAKA",
    num_lgd_state_code: 29,
    count: 61,
    number_of_proposal_submitted: 699,
  },
  {
    state: "KERALA",
    num_lgd_state_code: 32,
    count: 32,
    number_of_proposal_submitted: 300,
  },
  {
    state: "MADHYA PRADESH",
    num_lgd_state_code: 23,
    count: 29,
    number_of_proposal_submitted: 233,
  },
  {
    state: "MAHARASHTRA",
    num_lgd_state_code: 27,
    count: 61,
    number_of_proposal_submitted: 561,
  },
  {
    state: "MANIPUR",
    num_lgd_state_code: 14,
    count: 4,
    number_of_proposal_submitted: 20,
  },
  {
    state: "MEGHALAYA",
    num_lgd_state_code: 17,
    count: 2,
    number_of_proposal_submitted: 20,
  },
  {
    state: "MIZORAM",
    num_lgd_state_code: 15,
    count: 7,
    number_of_proposal_submitted: 28,
  },
  {
    state: "NAGALAND",
    num_lgd_state_code: 13,
    count: 2,
    number_of_proposal_submitted: 13,
  },
  {
    state: "ODISHA",
    num_lgd_state_code: 21,
    count: 29,
    number_of_proposal_submitted: 289,
  },
  {
    state: "PUDUCHERRY",
    num_lgd_state_code: 34,
    count: 4,
    number_of_proposal_submitted: 67,
  },
  {
    state: "PUNJAB",
    num_lgd_state_code: 3,
    count: 42,
    number_of_proposal_submitted: 348,
  },
  {
    state: "RAJASTHAN",
    num_lgd_state_code: 8,
    count: 28,
    number_of_proposal_submitted: 242,
  },
  {
    state: "TAMIL NADU",
    num_lgd_state_code: 33,
    count: 90,
    number_of_proposal_submitted: 1679,
  },
  {
    state: "TELANGANA",
    num_lgd_state_code: 36,
    count: 57,
    number_of_proposal_submitted: 559,
  },
  {
    state: "TRIPURA",
    num_lgd_state_code: 16,
    count: 2,
    number_of_proposal_submitted: 29,
  },
  {
    state: "UTTARAKHAND",
    num_lgd_state_code: 5,
    count: 29,
    number_of_proposal_submitted: 221,
  },
  {
    state: "UTTAR PRADESH",
    num_lgd_state_code: 9,
    count: 86,
    number_of_proposal_submitted: 742,
  },
  {
    state: "WEST BENGAL",
    num_lgd_state_code: 19,
    count: 94,
    number_of_proposal_submitted: 467,
  },
];
